### ISSUE TITLE
BUG: GUI Navigation to go back in folder hierarchy do not work

### ISSUE THREAD

**Issue by dee22** [ctf0/demos#10]
How can i navigate back from a Folder? The **Breadcrumb** and **Close** Options at the Bottom are not clickable and enter an other Folder in the URI does not affect the folder i'm in.. Only way it works is with Backspace.. Is that normal?

**Edit:**
Mobile version (small screen):
- Anything works as expected, except direct URI manipulation.
- direct URI manipulation do not work.

Desktop version:
- Only Backspace works.
- Breadcrumb Navigation, Close Button and direct URI manipulation do not work.

Tested with Edge, Chrome and FF.

**Comment by Alvazz** [comment]
is a bug, i fixed it.

**Comment by ctf0** [comment]
@dee22 not its not normal, i will re-check.
@Alvazz if u have a solution could u make a PR to the original repo ?

**Comment by Alvazz** [comment]
@ctf0 busy..i will do it later ..

**Comment by ctf0** [comment]
@dee22 can u plz open a new ticket on the main repo ?

**Comment by dee22** [comment]
@ctf0 i'll test it soon if the bug is also present when i install it from the main repo.
If this is the case i'll open a new ticket.

**Comment by dee22** [comment]
I have tested it and the bug is still present in the Main Repo.
There is already an open bug-report ctf0/Laravel-Media-Manager#99 which describes the same issue..

**Comment by ctf0** [comment]
okay, i will close this one then and continue over the main one, thanx for the headsup
