### ISSUE TITLE
Can you add "Use the manager From A Modal" and "Use The Manager With Any WYSIWYG Editor" functions to this demo?

### ISSUE THREAD

**Issue by trungdung1995** [ctf0/demos#3]
I got error when I setup two functions that. Can you add that to demo? Thank you so much!

**Comment by ctf0** [comment]
sorry not possible because this requires creating extra model & UI which is not related to the demo.

maybe u can open a ticket on the original repo with what exactly is u r facing & i'll try to help u fix it

**Comment by trungdung1995** [comment]
Ok, I am amateur. I hope you will help me to complete my project. Thanks!
