### ISSUE TITLE
Error compiling template

### ISSUE THREAD

**Issue by kennj2016** [ctf0/demos#5]
![image](https://user-images.githubusercontent.com/20420858/50262482-28c81800-0444-11e9-8c4d-893c194b3cfb.png)

**Comment by ctf0** [comment]
more details please

**Comment by Serzhs** [comment]
I have the same Error, iv'e done [DEMO steps](https://github.com/ctf0/demos/tree/media-manager)

**Comment by ctf0** [comment]
@Espumisan the demo would give errors because of the new laravel-mix V4, so plz open a new ticket with info of what exactly u r getting
