### ISSUE TITLE
TypeError: Cannot read property 'ratioBar' of undefined

### ISSUE THREAD

**Issue by Serzhs** [ctf0/demos#6]
Hello, I did [DEMO](https://github.com/ctf0/demos/tree/media-manager) step by step and at the end i recieve error with message `TypeError: Cannot read property 'ratioBar' of undefined` and some Vue warining.

Image: 
![2019-01-30_1320](https://user-images.githubusercontent.com/5610063/51978101-d857c780-2491-11e9-961f-0ee25afd5a16.png)

**Comment by ctf0** [comment]
thank you for reporting, i'll check when possible, for now can u try with laravel-mix v2 or v3 ?

**Comment by Espumisan** [comment]
I tried v3 but images are not showing:
`Uncaught (in promise) TypeError: Failed to fetch`

**Comment by Serzhs** [comment]
I't works with mix v3

**Comment by ctf0** [comment]
good, thanx for retesting, i'll try to fix the v4 this week or will add a note to the readme about v3

https://github.com/ctf0/Laravel-Media-Manager/issues/71

ref: https://laravel-mix.com/docs/4.0/upgrade#notes

**Comment by ctf0** [comment]
@Espumisan, can u plz try to install laravel mix v4 and update the `Vue.component` call in [manager.js](https://github.com/ctf0/demos/blob/media-manager/resources/assets/vendor/MediaManager/js/manager.js) with `.default` ex.

```js
Vue.component('icon', require('vue-awesome/components/Icon').default)
Vue.component('MediaManager', require('./components/media.vue').default)
Vue.component('MyNotification', require('vue-notif').default)
```

and reply back with ur findings ?
