### ISSUE TITLE
$pattern not defined

### ISSUE THREAD

**Issue by tosh2** [ctf0/demos#7]
Hi, i've been getting this error on the "Laravel media manager", this is the output

ErrorException (E_ERROR)
Undefined variable: patterns (View: /home/tosh/testing/media-manager/resources/views/vendor/MediaManager/_manager.blade.php) (View: /home/tosh/testing/media-manager/resources/views/vendor/MediaManager/_manager.blade.php)

i've tried to use mysql ( https://github.com/ctf0/Laravel-Media-Manager/wiki/Lock-Files-&-Folder ), correct me if im wrong, the order to execute the commands in the link above are ... configuring the connection first and then migrating or deleting the sqlite file (i don't know if this has anything to do with the error lol )

**Comment by ctf0** [comment]
plz update ur installation with https://github.com/ctf0/Laravel-Media-Manager/blob/master/src/resources/views/_manager.blade.php#L50

ref: https://github.com/ctf0/Laravel-Media-Manager/issues/74

**Comment by ctf0** [comment]
for the lock files option, plz open a new issue with exact error u r getting

**Comment by tosh2** [comment]
@ctf0 Thanks, i got it up and running, it was just that one line !!

**Comment by ctf0** [comment]
awesome
