### ISSUE TITLE
Demo not working for Laravel 5.8

### ISSUE THREAD

**Issue by pedzed** [ctf0/demos#8]
![image](https://user-images.githubusercontent.com/8146593/56173400-a9131a00-5fed-11e9-95ea-3805a60a0e6f.png)

**Comment by pedzed** [comment]
Apparently you have to rerun `npm run dev` (or `watch`?)

```
        Okay, done. The following packages have been installed and saved to your package.json dependencies list:
 
 	- sass-loader@7.*
 
 	- sass
 
 	- resolve-url-loader@2.3.1
 
 	Finished. Please run Mix again.
```

Now it works, but there are still some errors and warnings:

![image](https://user-images.githubusercontent.com/8146593/56173561-6f8ede80-5fee-11e9-975d-753071df88c0.png)

I believe this is not related to the demo though, but rather the package.

**Comment by ctf0** [comment]
can u expand the errors so i can see what have actually went wrong ?

**update**
i made some fixes according to the ss, try to `composer update` and republish the assets & see it solved the issue
